
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/mizanul/Documents/code/Tkinter-Designer/build/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#85C13D")

window.attributes('-fullscreen', True)

# Fungsi untuk keluar dari fullscreen
def exit_fullscreen(event=None):
    window.attributes('-fullscreen', False)

# Klik tombol "Esc" 
window.bind("<Escape>", exit_fullscreen)


canvas = Canvas(
    window,
    bg = "#85C13D",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    544.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    960.0,
    592.0,
    image=image_image_2
)

canvas.create_text(
    626.0,
    713.0,
    anchor="nw",
    text="Testing ukuran layar",
    fill="#14181F",
    font=("Nunito Regular", 19 * -1)
)

canvas.create_text(
    626.0,
    754.0,
    anchor="nw",
    text="Apakah ini cocok?",
    fill="#404040",
    font=("Nunito Bold", 26 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    960.0,
    526.0,
    image=image_image_3
)

canvas.create_rectangle(
    654.0,
    1075.0,
    1267.0,
    1080.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    957.9999899900922,
    850.999999781443,
    963.0000100135803,
    1080.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1914.9999732049191,
    238.99999978144297,
    1920.0,
    852.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1690.999999562885,
    542.9999899864197,
    1920.0,
    548.0000200198156,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1.0,
    238.99999978144297,
    6.000026795080885,
    852.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1.0,
    542.9999899864197,
    230.00000043711498,
    548.0000200198156,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    654.0,
    0.0,
    1267.0,
    5.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    958.000000063178,
    4.999999781443876,
    963.0,
    309.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()
