
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\ENT Project\export\v2\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#85C13D")


canvas = Canvas(
    window,
    bg = "#85C13D",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    577.0,
    318.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    567.0,
    319.5,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    909.0,
    515.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=893.0,
    y=499.0,
    width=31.0,
    height=31.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1223.0,
    318.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1222.55078125,
    269.0,
    image=image_image_5
)

canvas.create_text(
    1038.0,
    83.0,
    anchor="nw",
    text="Analisa Gambar:",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

canvas.create_text(
    1038.0,
    424.0,
    anchor="nw",
    text="Keterangan grafik:",
    fill="#404040",
    font=("Nunito Regular", 14 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1062.0,
    470.5,
    image=image_image_6
)

canvas.create_text(
    1084.0,
    459.0,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

canvas.create_text(
    1084.0,
    491.0,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1062.0,
    502.5,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    1062.0,
    534.5,
    image=image_image_8
)

canvas.create_text(
    1084.0,
    523.0,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    567.0,
    765.0,
    image=image_image_9
)

canvas.create_text(
    176.0,
    635.0,
    anchor="nw",
    text="Hasil Diagnosa",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

canvas.create_text(
    176.0,
    695.0,
    anchor="nw",
    text="OMA PERFORASI",
    fill="#1E5C2A",
    font=("Nunito Bold", 30 * -1)
)

canvas.create_text(
    176.0,
    739.0,
    anchor="nw",
    text="OMA Perforasi adalah gangguan pada telinga tengah yang dicirikan dengan adanya lubang pada gendang telinga. OMA Perforasi sering menyebabkan keluarnya cairan dari telinga dan dapat disertai dengan rasa nyeri serta gangguan pendengaran.",
    fill="#404040",
    font=("Nunito SemiBold", 16 * -1)
)

canvas.create_text(
    176.0,
    818.0,
    anchor="nw",
    text="Tingkat keyakinan dignosa: 65%",
    fill="#404040",
    font=("Nunito Regular", 14 * -1)
)

canvas.create_text(
    176.0,
    854.0,
    anchor="nw",
    text="Note: Jika hasil diagnosa dirasa keliru, silakan untuk melakukan koreksi hasil.",
    fill="#151920",
    font=("Nunito Bold", 12 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    1223.0,
    765.0,
    image=image_image_10
)

canvas.create_text(
    1038.0,
    635.0,
    anchor="nw",
    text="Informasi Pasien",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

canvas.create_text(
    1038.0,
    685.0,
    anchor="nw",
    text="Alma Liakua Mutia",
    fill="#404040",
    font=("Nunito Bold", 20 * -1)
)

canvas.create_text(
    1038.0,
    719.0,
    anchor="nw",
    text="No Asuransi     : ",
    fill="#404040",
    font=("Nunito Regular", 15 * -1)
)

canvas.create_text(
    1151.0,
    719.0,
    anchor="nw",
    text="000863002321023",
    fill="#404040",
    font=("Nunito Bold", 15 * -1)
)

canvas.create_text(
    1038.0,
    743.0,
    anchor="nw",
    text="Jenis Asuransi  : ",
    fill="#404040",
    font=("Nunito Regular", 15 * -1)
)

canvas.create_text(
    1150.0,
    743.0,
    anchor="nw",
    text="BPJS",
    fill="#404040",
    font=("Nunito Bold", 15 * -1)
)

canvas.create_text(
    1038.0,
    767.0,
    anchor="nw",
    text="Kelas Asuransi : ",
    fill="#404040",
    font=("Nunito Regular", 15 * -1)
)

canvas.create_text(
    1150.0,
    767.0,
    anchor="nw",
    text="Kelas 1",
    fill="#404040",
    font=("Nunito Bold", 15 * -1)
)

canvas.create_text(
    1038.0,
    791.0,
    anchor="nw",
    text="Fasilitas Kesehatan : ",
    fill="#404040",
    font=("Nunito Regular", 15 * -1)
)

canvas.create_text(
    1177.0,
    791.0,
    anchor="nw",
    text="Puskesmas Selaparang",
    fill="#404040",
    font=("Nunito Bold", 15 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    70.99998474121094,
    490.9999945797865,
    image=image_image_11
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=49.0,
    y=467.0,
    width=46.0,
    height=46.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=53.99999847010076,
    y=400.99999847010145,
    width=35.00000152989924,
    height=35.000001529898555
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=57.0,
    y=618.0,
    width=28.0,
    height=28.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=58.0,
    y=342.0,
    width=28.0,
    height=28.0
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    70.99999812041096,
    561.9999981204103,
    image=image_image_12
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=58.0,
    y=549.0,
    width=28.0,
    height=28.0
)
window.resizable(False, False)
window.mainloop()
