
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\ENT Project\export\v2\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#85C13D")


canvas = Canvas(
    window,
    bg = "#85C13D",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    548.0,
    487.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    548.0,
    486.5,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=871.0,
    y=803.0,
    width=52.0,
    height=52.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1209.0,
    712.0,
    image=image_image_3
)

canvas.create_text(
    1009.0,
    768.0,
    anchor="nw",
    text="Alasan",
    fill="#404040",
    font=("Nunito Bold", 19 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1209.0,
    838.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1019.0,
    y=802.0,
    width=380.0,
    height=70.0
)

canvas.create_text(
    1009.0,
    669.0,
    anchor="nw",
    text="Label Baru",
    fill="#404040",
    font=("Nunito Bold", 19 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1009.0,
    y=704.0,
    width=400.0,
    height=32.0
)

canvas.create_text(
    1009.0,
    585.0,
    anchor="nw",
    text="Untuk mengoreksi hasil diagnosa sebelumnya, mohon untuk memilih label berikut yang dinilai sesuai dengan penyakit yang diderita pasien dan sertakan alasan yang jelas.",
    fill="#14181F",
    font=("Nunito Regular", 14 * -1)
)

canvas.create_text(
    1009.0,
    537.0,
    anchor="nw",
    text="Koreksi Hasil",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1209.0,
    276.0,
    image=image_image_4
)

canvas.create_text(
    1009.0,
    92.0,
    anchor="nw",
    text="Analisa Gambar:",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1209.0,
    254.0,
    image=image_image_5
)

canvas.create_text(
    1009.0,
    385.0,
    anchor="nw",
    text="Keterangan grafik:",
    fill="#404040",
    font=("Nunito Regular", 14 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1033.0,
    439.0,
    image=image_image_6
)

canvas.create_text(
    1055.0,
    427.5,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1152.0,
    439.0,
    image=image_image_7
)

canvas.create_text(
    1174.0,
    427.5,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    1272.0,
    439.0,
    image=image_image_8
)

canvas.create_text(
    1294.0,
    427.5,
    anchor="nw",
    text="OMA Perforasi",
    fill="#404040",
    font=("Nunito Regular", 12 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    70.99998474121094,
    490.9999945797865,
    image=image_image_9
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=49.0,
    y=467.0,
    width=46.0,
    height=46.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=53.99999847010076,
    y=400.99999847010145,
    width=35.00000152989924,
    height=35.000001529898555
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=57.0,
    y=618.0,
    width=28.0,
    height=28.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=58.0,
    y=342.0,
    width=28.0,
    height=28.0
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    70.99999812041096,
    561.9999981204103,
    image=image_image_10
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=58.0,
    y=549.0,
    width=28.0,
    height=28.0
)
window.resizable(False, False)
window.mainloop()
