
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\ENT Project\export\controller\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1133x744")
window.configure(bg = "#85C13D")


canvas = Canvas(
    window,
    bg = "#85C13D",
    height = 744,
    width = 1133,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=41.0,
    y=255.0,
    width=332.0,
    height=319.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=402.0,
    y=255.0,
    width=330.0,
    height=319.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=761.0,
    y=255.0,
    width=332.0,
    height=319.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    566.0,
    89.0,
    image=image_image_1
)

canvas.create_text(
    281.0,
    608.0,
    anchor="nw",
    text="Silakan pilih diagnosa yang akan anda lakukan. \nKami akan menyiapkannya untuk anda.",
    fill="#FFFFFF",
    font=("Nunito SemiBold", 16 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1099.333251953125,
    22.33349609375,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1074.0,
    22.33056640625,
    image=image_image_3
)

canvas.create_text(
    21.0,
    13.0,
    anchor="nw",
    text="9:41",
    fill="#FFFFFF",
    font=("SFProText Semibold", 15 * -1)
)

canvas.create_text(
    130.0,
    117.5,
    anchor="nw",
    text="RS. Universitas Mataram",
    fill="#FFFFFF",
    font=("Nunito Black", 14 * -1)
)

canvas.create_text(
    130.0,
    144.5,
    anchor="nw",
    text="Unit THT",
    fill="#F1F1F1",
    font=("Nunito SemiBold", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    89.0,
    139.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
