
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\ENT Project\export\controller\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1133x744")
window.configure(bg = "#85C13F")


canvas = Canvas(
    window,
    bg = "#85C13F",
    height = 744,
    width = 1133,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    566.0,
    378.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    566.0,
    292.5,
    image=image_image_2
)

canvas.create_text(
    65.0,
    589.0,
    anchor="nw",
    text="Pastikan gambar terlihat dengan jelas dan memiliki posisi sempurna. Jika gambar terlihat kurang sempurna silakan untuk mengambil ulang gambar.",
    fill="#14181F",
    font=("Nunito Regular", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=370.5,
    y=631.0,
    width=192.0,
    height=54.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=570.5,
    y=631.0,
    width=192.0,
    height=54.0
)

canvas.create_text(
    65.0,
    541.0,
    anchor="nw",
    text="Gambar Berhasil Diambil!",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1099.333251953125,
    22.33349609375,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1074.0,
    22.33056640625,
    image=image_image_4
)

canvas.create_text(
    21.0,
    13.0,
    anchor="nw",
    text="9:41",
    fill="#FFFFFF",
    font=("SFProText Semibold", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
