
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\ENT Project\export\controller\build\assets\frame7")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1133x744")
window.configure(bg = "#86C141")


canvas = Canvas(
    window,
    bg = "#86C141",
    height = 744,
    width = 1133,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    376.0,
    378.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    370.0,
    377.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    904.0,
    295.0,
    image=image_image_3
)

canvas.create_text(
    749.0,
    75.0,
    anchor="nw",
    text="Koreksi Hasil",
    fill="#404040",
    font=("Nunito Bold", 24 * -1)
)

canvas.create_text(
    749.0,
    123.0,
    anchor="nw",
    text="Untuk mengoreksi hasil diagnosa sebelumnya, mohon untuk memilih label berikut yang dinilai sesuai dengan penyakit yang diderita pasien dan sertakan alasan yang jelas.",
    fill="#14181F",
    font=("Nunito Regular", 14 * -1)
)

canvas.create_text(
    749.0,
    227.0,
    anchor="nw",
    text="Label Baru",
    fill="#404040",
    font=("Nunito Bold", 19 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=749.0,
    y=262.0,
    width=310.0,
    height=40.0
)

canvas.create_text(
    749.0,
    334.0,
    anchor="nw",
    text="Alasan",
    fill="#404040",
    font=("Nunito Bold", 19 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    904.0,
    404.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=759.0,
    y=368.0,
    width=290.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=750.0,
    y=463.0,
    width=150.0,
    height=46.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=908.0,
    y=463.0,
    width=150.0,
    height=46.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1099.3330078125,
    22.33349609375,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1074.0,
    22.33056640625,
    image=image_image_5
)

canvas.create_text(
    21.0,
    13.0,
    anchor="nw",
    text="9:41",
    fill="#FFFFFF",
    font=("SFProText Semibold", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
